name: Annotation
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::error::This is an error message"
          echo "::warning::This is a warning message"
          echo "::notice::This is a notice message"
          echo "::info::This is an info message"
          echo "::debug::This is a debug message"
          echo "::trace::This is a trace message"
