name: Func
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ello') }}
          STARTS_FUNC: ${{ startsWith('Hello', 'Hel') }}
          ENDS_FUNC: ${{ endsWith('Hello', 'lo') }}
          CONTAINS_ARRAY: ${{ contains(github.event.issue.labels.*.name, 'bug') }}
